name: nek-type-a
channels:
  - conda-forge
dependencies:
  - python=2.7.15
  - numpy
  - scipy
  - numba
  - quaternion
  - svgwrite
  - pip:
    - cadquery==1.2.0
    - pyparsing==2.2.0
    - virtualenv==16.0.0
    - svgpathtools==1.3.2
    - future-fstrings
    - pyclipper==1.1.0